"use client";

import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./ui/header";
import { useState } from "react";
import clsx from "clsx";

const inter = Inter({ subsets: ["latin"] });
const montserrat = Montserrat({
  weight: ['400', '500', '600', '700', '800', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin']
})

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [nightMode, setNightMode] = useState(true);
  return (
    <html lang="en">
      <body className={clsx(`${montserrat.className}`, {
          'bg-[#212E37] text-white': nightMode,
          'bg-white text-[#212E37]': !nightMode
        })}>
        <Header nightMode={nightMode} setNightMode={setNightMode} />
        {children}
      </body>
    </html>
  );
}
